
###POST user
POST http://localhost:3004/users HTTP/1.1
content-type: application/json

{
    "name": "Andrew Mead",
    "email": "andrew@example.com",
    "password": "12345678"
}

###login user
POST http://localhost:3004/users/login HTTP/1.1
content-type: application/json

{
    "email": "andrew@example.com",
    "password": "12345678"
}


###signup user
POST http://localhost:3004/users/signup HTTP/1.1
content-type: application/json

{
    "name": "Andrew Mead",
    "email": "andrew@example.com",
    "password": "12345678"
}

###signup user
POST http://localhost:3004/users/signup HTTP/1.1
content-type: application/json

{
  "name": "Minh",
  "email": "minh@example.com",
  "password": "12345678"
}

###signup user
POST http://localhost:3004/users/signup HTTP/1.1
content-type: application/json

{
  "name": "Tuan",
  "email": "tuan@example.com",
  "password": "12345678",
  "age": 29
}

###signup user
POST http://localhost:3004/users/signup HTTP/1.1
content-type: application/json

{
  "name": "Hoang",
  "email": "hoang@example.com",
  "password": "12345678",
  "age" : 33
}

###signup user
POST http://localhost:3004/users/signup HTTP/1.1
content-type: application/json

{
  "name": "Nam",
  "email": "nam@example.com",
  "password": "12345678",
  "age" : 34
}

### add avatar
POST http://localhost:3004/users/me/avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkzNDdkNTQ4ZWYwN2YwNDJlMjQ2MjUiLCJpYXQiOjE2NzA1OTY1NjV9.ZRMN5iWa_X18koEklJeK_Q7ClUDUCV8IARRwv_zq-SI
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="related-1.jpg"
Content-Type: image/jpeg

< ./related-1.jpg

--boundary--

### remove avatar
DELETE http://localhost:3004/users/me/avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkzNDdkNTQ4ZWYwN2YwNDJlMjQ2MjUiLCJpYXQiOjE2NzA1OTY1NjV9.ZRMN5iWa_X18koEklJeK_Q7ClUDUCV8IARRwv_zq-SI
content-type: application/json

### get avatar
DELETE http://localhost:3004/users/me/avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkzNDdkNTQ4ZWYwN2YwNDJlMjQ2MjUiLCJpYXQiOjE2NzA1OTY1NjV9.ZRMN5iWa_X18koEklJeK_Q7ClUDUCV8IARRwv_zq-SI
content-type: application/json

###PATCH user
PATCH http://localhost:3004/users/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkwYTQ4NGJhNDA0OGMxNjk2NWYxYWIiLCJpYXQiOjE2NzA0MjM2ODh9.WdXMtWsMmU9Cf4AP1E6E5dDtXgIib3dImc4sqqvix6I
content-type: application/json

{
    "name": "Minh",
    "password": "12345678"
}

###DELETE user
DELETE http://localhost:3004/users/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkxNzQ5ZTRiZWNiOWNiOWI2ODM1NWMiLCJpYXQiOjE2NzA0NzY5NTh9.cIZ3FJVJI3c7o7H0recTybgbwZE8bwXnLuNMfnE6ZS4
content-type: application/json

###GET user profile
GET http://localhost:3004/users/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkwYTQ4NGJhNDA0OGMxNjk2NWYxYWIiLCJpYXQiOjE2NzA0MjM2ODh9.WdXMtWsMmU9Cf4AP1E6E5dDtXgIib3dImc4sqqvix6I
content-type: application/json

###logout
POST http://localhost:3004/users/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzhlZTg2MjYyZDg5MDM1ZjM5YmNhMjIiLCJpYXQiOjE2NzA0MDI2OTh9.aoneU95dV197l7E6Yypl11m_h_loupcf8c6p3yG1BFE
content-type: application/json
###logout All
POST http://localhost:3004/users/logoutAll HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzhlZTg2MjYyZDg5MDM1ZjM5YmNhMjIiLCJpYXQiOjE2NzA0MDE1NzV9.P7fNgt52s6WMEpejcHYEy2tUarALXXEsXQZRvC7ExFo
content-type: application/json

### POST task
POST http://localhost:3004/tasks HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzk0NGI5ZDA0OTk5MzQyMDZkNWE3YjUiLCJpYXQiOjE2NzA2NjMwNjl9.wYroero_t7417sCfDTgbu17jaIZHedjnIC4_CNiDGM8
content-type: application/json

{
    "description": "Go to office",
    "completed": true
}
### POST task
POST http://localhost:3004/tasks HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkyZjlkNTIyOTMzMTcxZGY5Njg0Y2YiLCJpYXQiOjE2NzA1NzY1OTd9.S1bDfr6AarH7bCu0Djo2kWacunulEJG7PaTd0VUfB7U
content-type: application/json

{
    "description": "Go to train4",
    "completed": true
}

### PATCH task
PATCH http://localhost:3004/tasks/6391762b251c17dd7a535b9d HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkxNzQ5ZTRiZWNiOWNiOWI2ODM1NWMiLCJpYXQiOjE2NzA0NzY5NTh9.cIZ3FJVJI3c7o7H0recTybgbwZE8bwXnLuNMfnE6ZS4
content-type: application/json

{
    "completed": true
}

### DELETE task
DELETE http://localhost:3004/tasks/639179f6f03461cac6e03c39 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkxNzQ5ZTRiZWNiOWNiOWI2ODM1NWMiLCJpYXQiOjE2NzA0NzY5NTh9.cIZ3FJVJI3c7o7H0recTybgbwZE8bwXnLuNMfnE6ZS4
content-type: application/json


### GET tasks
GET http://localhost:3004/tasks?sortBy=createdAt:desc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzk0NGI5ZDA0OTk5MzQyMDZkNWE3YjUiLCJpYXQiOjE2NzA2NjMwNjl9.wYroero_t7417sCfDTgbu17jaIZHedjnIC4_CNiDGM8

### GET tasks
GET http://localhost:3004/tasks/63916e36f1b58ab889c0eeb3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkxNzQ5ZTRiZWNiOWNiOWI2ODM1NWMiLCJpYXQiOjE2NzA0NzY5NTh9.cIZ3FJVJI3c7o7H0recTybgbwZE8bwXnLuNMfnE6ZS4

### ---------------------------- UPLOAD FEED IMAGES ----------------------------
POST http://localhost:3004/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="upload"; filename="related-1.png2"
Content-Type: image/jpeg

< ./related-1.jpg

--boundary--
### -------------------------------------------------------------------------
