
###POST user
POST http://localhost:3004/users HTTP/1.1
content-type: application/json

{
    "name": "Andrew Mead",
    "email": "andrew@example.com",
    "password": "12345678"
}

###login user
POST http://localhost:3004/users/login HTTP/1.1
content-type: application/json

{
    "email": "andrew@example.com",
    "password": "12345678"
}
###signup user
POST http://localhost:3004/users/signup HTTP/1.1
content-type: application/json

{
    "name": "Andrew Mead 3",
    "email": "andrew3@example.com",
    "password": "12345678"
}

###PATCH user
PATCH http://localhost:3004/users/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkwYTQ4NGJhNDA0OGMxNjk2NWYxYWIiLCJpYXQiOjE2NzA0MjM2ODh9.WdXMtWsMmU9Cf4AP1E6E5dDtXgIib3dImc4sqqvix6I
content-type: application/json

{
    "name": "Minh",
    "password": "12345678"
}

###DELETE user
DELETE http://localhost:3004/users/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzhlZTg2MjYyZDg5MDM1ZjM5YmNhMjIiLCJpYXQiOjE2NzA0MjM1MzZ9.VH2lZeZwnC0DZ-Prq0rG3I7bGMp12XqaBob-yf_VReU
content-type: application/json

###GET user profile
GET http://localhost:3004/users/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzkwYTQ4NGJhNDA0OGMxNjk2NWYxYWIiLCJpYXQiOjE2NzA0MjM2ODh9.WdXMtWsMmU9Cf4AP1E6E5dDtXgIib3dImc4sqqvix6I
content-type: application/json

###logout
POST http://localhost:3004/users/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzhlZTg2MjYyZDg5MDM1ZjM5YmNhMjIiLCJpYXQiOjE2NzA0MDI2OTh9.aoneU95dV197l7E6Yypl11m_h_loupcf8c6p3yG1BFE
content-type: application/json
###logout All
POST http://localhost:3004/users/logoutAll HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzhlZTg2MjYyZDg5MDM1ZjM5YmNhMjIiLCJpYXQiOjE2NzA0MDE1NzV9.P7fNgt52s6WMEpejcHYEy2tUarALXXEsXQZRvC7ExFo
content-type: application/json

### POST task
POST http://localhost:3004/tasks HTTP/1.1
content-type: application/json

{
    "description": "Read mail",
    "completed": false
}

### PUT task
PATCH http://localhost:3004/tasks/6385b83b741737e0c51df32c HTTP/1.1
content-type: application/json

{
    "completed": true
}

### DELETE task
DELETE http://localhost:3004/tasks/6385b83b741737e0c51df32c HTTP/1.1
content-type: application/json


### GET tasks
GET http://localhost:3004/tasks HTTP/1.1

### GET tasks
GET http://localhost:3004/tasks/6385b86a51902b1925997c4f HTTP/1.1

